In [80]:
import numpy as np
import pandas as pd
%matplotlib inline
import seaborn as sns
import matplotlib.pyplot as plt
# 그래프 한글 처리하는 코드
import platform
from scipy.stats import *
from matplotlib import font_manager, rc
plt.rcParams['axes.unicode_minus'] = False

if platform.system() == 'Darwin':  # 맥OS 
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows': 
    # 윈도우   
    path = "c:/Windows/Fonts/malgun.ttf"
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system...  sorry~~~')

# 클래스와 메서드

In [1]:
class cat :
    def meow() :
        print('야옹')

In [2]:
cat.meow()

야옹


In [5]:
cats = cat()

In [30]:
print(cats.meow)

<bound method cat.meow of <__main__.cat object at 0x00000286789C1340>>


In [21]:
class cat :
    def __init__(self, name, color):
        self.name = name
        self.color = color
    def info(self) :
        print('cat\'s name is ',self.name, ', color is ', self.color)

In [28]:
cat1 = cat('choco','yellow')
cat1

In [43]:
class Man : 
    def __init__(self, name) :
        self.name = name
        print('Init!')
    def hello(self) :
        print('hello! ',self.name)
    def bye(self) :
        print('Goodbye ',selfname)
# 오류
# hello() takes 0 positional arguments but 1 was given
# hello()는 인자 받지 않는데 1개가 들어갔다

In [44]:
m = Man('yeseul')

Init!


In [45]:
m.hello()

hello  yeseul


dir(Man)

# numpy 원소접근

In [53]:
X = ([51,55],[14,19],[0,4])

In [54]:
X

([51, 55], [14, 19], [0, 4])

In [61]:
X = np.array([[51,55],[14,19],[0,4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [62]:
X[0][1]

55

In [64]:
X=X.flatten()
print(X)

[51 55 14 19  0  4]


In [65]:
X[np.array([0,2,4])]

array([51, 14,  0])

In [67]:
np.array([0,2,4])

array([0, 2, 4])

In [72]:
X[0]

51

# 퍼셉트론 구현하기

In [78]:
def AND(x1, x2) :
    w1, w2, theta = 0.5, 0.5, 0.7
    tmp = x1*w1 + x2+w2
    if tmp <= theta :
        return 0
    elif tmp > theta : 
        return 1

In [79]:
AND(0,0), AND(0,1), AND(1,0), AND(1,1)

(0, 1, 1, 1)

In [81]:
import numpy as np

In [84]:
x =  np.array([0,1]) # 입력
w = np.array([0.5,0.5]) # 가중치
b = -0.7
x*w
np.sum(x*w) + b

-0.19999999999999996

In [88]:
def AND(x1,x2) :
    x = np.array([x1,x2])
    w = np.array([0.5,0.5])
    b = -0.7
    tmp = np.sum(x*w) + b
    if tmp <= 0 :
        return 0 
    else :
        return 1

In [90]:
AND(0,0), AND(1,0), AND(0,1), AND(1,1)

(0, 0, 0, 1)

In [99]:
def NAND(x1,x2) : 
    x = np.array([x1,x2])
    w = np.array([-0.5,-0.5])
    b = 0.7
    tmp = np.sum(x*w) + b
    if tmp <= 0 :
        return 0
    else :
        return 1
    
def OR(x1,x2) : 
    x = np.array([x1,x2])
    w = np.array([0.5,0.5])
    b = -0.2
    tmp = np.sum(x*w) + b
    if tmp <= 0 :
        return 0
    else :
        return 1

In [97]:
NAND(0,0), NAND(1,0), NAND(0,1), NAND(1,1)

(1, 1, 1, 0)

In [98]:
OR(0,0), OR(1,0), OR(0,1), OR(1,1)

(1, 1, 1, 1)

In [100]:
def XOR(x1,x2) : 
    s1 = NAND(x1,x2)
    s2 = OR(x1,x2)
    y = AND(s1,s2)
    return y

In [101]:
XOR(0,0), XOR(1,0), XOR(0,1), XOR(1,1) 

(0, 1, 1, 0)

In [ ]:
# 의도한대로 출력되지 않아 AND, NAND, OR 함수 검토를 했더니 OR이 틀려있었다
# 가중치 매개변수가 틀린 것을 적을 때 알아차리지 못해 아쉽다
# 그래도 XOR에서 문제가 있다는 것을 따로 계산해 알아차릴 수 있었다

In [ ]:
# 1,2장 후기 : 아직까진 어렵지 않고 재밌다.