In [6]:
import numpy as np

In [7]:
a = np.array([[-1.5, 0.5, 0.5], [2, 0, -1], [0.5, -0.5, 0.5]])

In [8]:
a = np.array([[4, 6, 2], [3, 4, 1], [2, 8, 13]])

In [9]:
b = np.array([9/4, -1/2, 2])

In [10]:
np.linalg.inv(a)

array([[-3.14285714,  4.42857143,  0.14285714],
       [ 2.64285714, -3.42857143, -0.14285714],
       [-1.14285714,  1.42857143,  0.14285714]])

In [11]:
b = np.array([[1, 1, 1],
     [3, 2, 1],
     [2, 1, 2]])

In [12]:
np.dot(a,b)

array([[26, 18, 14],
       [17, 12,  9],
       [52, 31, 36]])

In [13]:
def sigmoid(x) :
    return 1 / (1+np.exp(-x))

In [14]:
x = np.random.randn(10,2)
W1 = np.random.randn(2,4)
b1 = np.random.randn(4)
W2 = np.random.randn(4,3)
b2 = np.random.randn(3)

In [15]:
h = np.matmul(x,W1) + b1
a = sigmoid(h)
s = np.matmul(a, W2) + b2
s

array([[-3.44941442, -0.62785273,  0.19545374],
       [-1.76695791, -0.98579735, -0.52882226],
       [-1.4976196 , -1.00310946, -0.68241635],
       [-1.77423794, -0.96976101, -0.49099613],
       [-1.54990703, -0.87736027, -0.38121505],
       [-1.63154529, -0.81721608, -0.24404189],
       [-1.84766753, -0.64171319,  0.03713673],
       [-1.7990341 , -0.60355394,  0.07502115],
       [-1.91925096, -1.07127969, -0.65920972],
       [-3.57755786, -0.40562275,  0.38181288]])

In [16]:
class Sigmoid :
    def __init__(self):
        self.params = []
        
    def forward(self, x) :
        return 1 / (1+np.exp(-x))

In [17]:
class Affine :
    def __init__(self, W, b) :
        self.params = [W,b]
    
    def forward(self, x) :
        W, b = self.params
        out = np.matmul(x,W) +b
        return out

In [18]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size) :
        I, H, O = input_size, hidden_size, output_size
        
        # 가중치와 편향 초기화
        W1 = np.random.randn(I,H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H,O)
        b2 = np.random.randn(O)
        
        # 계층 생성
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]
        # 각 함수(레이어)별로 매개변수 지정 -> Affine.params = [W1,b2] 이런 식으로 저장됨
        
        # 모든 가중치를 리스트에 모은다
        self.params = []
        for layer in self.layers :
            self.params += layer.params
        
        # TwoLayerNet.params에 Affine.params, Sigmoid.params 등이 저장됨
        
    def predict(self, x) :
        for layer in self.layers:
            x = layer.forward(x)
        return x
        
        # 입력데이터 x가 Affine.forward, Sigmoid.forward 매소드로 전달됨

In [23]:
x= np.random.randn(10,2)
model = TwoLayerNet(2,4,3)
s= model.predict(x)

In [24]:
x

array([[-1.22524219, -0.35569904],
       [ 1.19994314, -1.72820656],
       [ 0.04291548,  0.37239753],
       [-0.32119193,  1.22884052],
       [ 0.98464464,  1.61337278],
       [ 0.13347583, -0.5633989 ],
       [-0.73170976, -0.81299974],
       [ 0.20378191,  0.39334698],
       [-1.11994562, -0.47757037],
       [ 1.64527715, -0.48889426]])

In [20]:
s

array([[ 1.80674722e+00, -1.45574736e-03, -1.03793318e+00],
       [ 1.77031801e+00, -1.60963780e-02, -1.07813242e+00],
       [ 1.56737303e+00, -2.80129811e-01, -1.31329822e+00],
       [ 1.87360857e+00,  4.42284375e-02, -9.14747167e-01],
       [ 1.58925247e+00,  1.32012867e-03, -1.20780413e+00],
       [ 1.70454547e+00,  9.71466197e-02, -1.08452724e+00],
       [ 1.68478026e+00, -7.31913145e-02, -1.16918279e+00],
       [ 1.73247285e+00,  9.37570315e-03, -1.10305042e+00],
       [ 1.48274784e+00, -3.77026809e-01, -1.43278025e+00],
       [ 1.50816383e+00, -2.12847141e-01, -1.35922555e+00]])

In [ ]:
# Repeat 노드

In [25]:
D, N = 8, 7
x = np.random.randn(1,D)
x

array([[-0.51385992, -1.04376836,  0.5262188 , -0.95525009,  0.60991532,
        -0.39859991, -0.1456503 ,  0.30844807]])

In [26]:
y = np.repeat(x, N, axis = 0) # 원소복제 수행, 배열 x를 N번 복제, axis 방향으로 복제
y

array([[-0.51385992, -1.04376836,  0.5262188 , -0.95525009,  0.60991532,
        -0.39859991, -0.1456503 ,  0.30844807],
       [-0.51385992, -1.04376836,  0.5262188 , -0.95525009,  0.60991532,
        -0.39859991, -0.1456503 ,  0.30844807],
       [-0.51385992, -1.04376836,  0.5262188 , -0.95525009,  0.60991532,
        -0.39859991, -0.1456503 ,  0.30844807],
       [-0.51385992, -1.04376836,  0.5262188 , -0.95525009,  0.60991532,
        -0.39859991, -0.1456503 ,  0.30844807],
       [-0.51385992, -1.04376836,  0.5262188 , -0.95525009,  0.60991532,
        -0.39859991, -0.1456503 ,  0.30844807],
       [-0.51385992, -1.04376836,  0.5262188 , -0.95525009,  0.60991532,
        -0.39859991, -0.1456503 ,  0.30844807],
       [-0.51385992, -1.04376836,  0.5262188 , -0.95525009,  0.60991532,
        -0.39859991, -0.1456503 ,  0.30844807]])

In [27]:
dy = np.random.randn(N,D)
dy

array([[ 0.08711007, -0.03625885,  2.10046258, -0.05679739,  0.43270964,
         1.28953935,  0.97013566, -0.13815527],
       [ 0.14533964,  0.16792786,  0.60727349, -0.80882314,  0.77811376,
         0.24078319,  0.20935929,  0.22760224],
       [ 0.66351727, -0.12213266, -0.55158269,  0.03521419, -0.74067892,
         0.01771666,  0.11512581,  0.23024494],
       [ 0.57244436,  0.10048124, -0.0943456 , -1.12516104, -0.27748097,
        -0.70115668, -0.71541845, -0.22936845],
       [ 0.10281684, -1.74384082,  1.24718703,  1.364152  , -0.28316951,
         0.50793277, -1.31700012, -0.4112539 ],
       [ 0.39423715, -0.53896368,  1.39680101,  2.53242755,  0.419721  ,
        -0.41314661, -1.60745352,  0.32693016],
       [ 1.89955557, -1.45529689,  1.20958423,  0.41622964, -0.13138844,
         0.26461457, -0.77390378,  0.76909442]])

In [29]:
dx = np.sum(dy, axis=0, keepdims = True) # keepdims 배열크기 유지
dx

array([[ 3.86502091, -3.6280838 ,  5.91538007,  2.35724181,  0.19782656,
         1.20628326, -3.1191551 ,  0.77509413]])

In [ ]:
# Sum 노드

In [30]:
D, N = 8, 7
x = np.random.randn(N,D)
x

array([[ 0.79781725,  1.51970595, -1.25227957,  0.54496929, -1.4497354 ,
        -0.28154585, -0.32555118, -0.20678197],
       [ 1.11993297,  0.76003097,  0.11810661, -0.49922859,  0.96089019,
         0.22386517,  1.12715125,  0.84583865],
       [-0.73851056, -0.47753678, -0.29440121, -0.35259353, -1.01157526,
         0.14567281,  0.16150837, -1.68743321],
       [ 1.51357913,  1.85776598,  0.98301834,  0.06979267, -0.15968205,
         0.22628812,  1.03830146, -0.3694317 ],
       [-0.59090574,  1.2432529 ,  0.79447284, -0.13205391,  0.28479181,
        -0.14934664,  0.48934759,  2.23762777],
       [ 1.4834494 , -0.01595735,  1.03753392, -2.23895511,  1.54205585,
         0.27219111,  1.06227692,  0.57971268],
       [ 0.36138644,  0.47191242,  1.38695935,  0.22095099, -0.87714279,
        -1.49583612, -0.20358083, -1.16222443]])

In [33]:
y = np.sum(x, axis=0, keepdims=True)
dy = np.random.randn(1,D)
dx = np.repeat(dy, N, axis=0)

In [ ]:
# Matmul 노드(행렬 곱셈)

In [34]:
class Matmul :
    def __init__(self, W) :
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None
    
    def forward(self, x) :
        W, = self.params
        out = np.matmul(x, W)
        self.x = x
        return out
    
    def backward(self, dout) :
        W, = self.params
        dx = np.matmul(dout, W.T)
        dW = np.matmul(self.x.T, dout)
        self.grads[0][...] = dW
        return dx

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [1]:
import sys
sys.path.append('..')
from dataset2 import spiral

In [2]:
import matplotlib.pyplot as plt

In [4]:
x,t = spiral.load_data()
print('x', x.shape)
print('t', t.shape)

x (300, 2)
t (300, 3)


In [6]:
x[1]
t[1]

array([1, 0, 0])

In [50]:
sys.path.append('..')
from common.layers import Affine, Sigmoid, SoftmaxWithLoss

In [71]:
class TwoLAyerNet :
    def __init__(self,input_size, hidden_size, output_size) :
        I,H,O = input_size, hidden_size, output_size
        
        # 가중치와 편향 초기화
        W1 = 0.01*np.random.randn(I,H)
        b1 = np.zeros(H)
        W2 = 0.01 * np.random.randn(H,O)
        b2 = np.zeros(O)
        
        # 계층생성
        self.layers = [
            Affine(W1,b1),
            Sigmoid(),
            Affine(W2,b2)
        ]
        self.loss_layer = SoftmaxWithLoss()


        # 모든 가중치와 기울기를 리스트에 모은다
        self.params, self.grads = [], []
        for layer in self.layers :
            self.params += layer.params
            self.grads +=layer.grads
            
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x
        
    def forward(self, x, t):
        score = self.predict(x)
        loss = self.loss_layer.forward(score, t)
        return loss


    def backward(self, dout=1):
        dout = self.loss_layer.backward(dout)
        for layer in reversed(self.layers) :
            dout = layer.backward(dout)
        return dout

In [43]:
from common.optimizer import SGD

In [77]:
# 하이퍼 파라미터 설정
max_epoch = 300
batch_size = 30
hidden_size = 10
learning_rate = 1.0

# 데이터 읽기, 모델과 옵티마이저 생성
x, t = spiral.load_data()
model = TwoLAyerNet(input_size=2, hidden_size=hidden_size, output_size=3)
optimizer = SGD(lr = learning_rate)


# 학습에 사용하는 변수
data_size = len(x)
max_iters = data_size // batch_size # 몫 구하기
total_loss = 0
loss_count = 0
loss_list = []

for epoch in range(max_epoch) :
    # 데이터 두섞기
    idx = np.random.permutation(data_size)
    x = x[idx]
    t = t[idx]
    
    for iters in range(max_iters) :
        batch_x = x[iters*batch_size:(iters+1)*batch_size] # x[0:10]...
        batch_t = t[iters*batch_size:(iters+1)*batch_size]

      # 기울기를 구해 매개변수 갱신
        loss = model.forward(batch_x, batch_t)
        model.backward()
        optimizer.update(model.params, model.grads)
        
        total_loss += loss
        loss_count += 1

        # 정기적으로 학습경과 출력
        if (iters+1) % 10 ==0 :
            avg_loss = total_loss / loss_count
            print('| 에폭 %d | 반복 %d / %d | 손실 %.2f' % (epoch+1, iters+1, max_iters, avg_loss))
            loss_list.append(avg_loss)
            total_loss, loss_count = 0, 0

| 에폭 1 | 반복 10 / 10 | 손실 1.13
| 에폭 2 | 반복 10 / 10 | 손실 1.13
| 에폭 3 | 반복 10 / 10 | 손실 1.12
| 에폭 4 | 반복 10 / 10 | 손실 1.12
| 에폭 5 | 반복 10 / 10 | 손실 1.11
| 에폭 6 | 반복 10 / 10 | 손실 1.14
| 에폭 7 | 반복 10 / 10 | 손실 1.16
| 에폭 8 | 반복 10 / 10 | 손실 1.11
| 에폭 9 | 반복 10 / 10 | 손실 1.12
| 에폭 10 | 반복 10 / 10 | 손실 1.13
| 에폭 11 | 반복 10 / 10 | 손실 1.12
| 에폭 12 | 반복 10 / 10 | 손실 1.11
| 에폭 13 | 반복 10 / 10 | 손실 1.09
| 에폭 14 | 반복 10 / 10 | 손실 1.08
| 에폭 15 | 반복 10 / 10 | 손실 1.04
| 에폭 16 | 반복 10 / 10 | 손실 1.03
| 에폭 17 | 반복 10 / 10 | 손실 0.96
| 에폭 18 | 반복 10 / 10 | 손실 0.92
| 에폭 19 | 반복 10 / 10 | 손실 0.92
| 에폭 20 | 반복 10 / 10 | 손실 0.87
| 에폭 21 | 반복 10 / 10 | 손실 0.85
| 에폭 22 | 반복 10 / 10 | 손실 0.82
| 에폭 23 | 반복 10 / 10 | 손실 0.79
| 에폭 24 | 반복 10 / 10 | 손실 0.78
| 에폭 25 | 반복 10 / 10 | 손실 0.82
| 에폭 26 | 반복 10 / 10 | 손실 0.78
| 에폭 27 | 반복 10 / 10 | 손실 0.76
| 에폭 28 | 반복 10 / 10 | 손실 0.76
| 에폭 29 | 반복 10 / 10 | 손실 0.78
| 에폭 30 | 반복 10 / 10 | 손실 0.75
| 에폭 31 | 반복 10 / 10 | 손실 0.78
| 에폭 32 | 반복 10 / 10 | 손실 0.77
| 에폭 33 | 반복 10 /

| 에폭 272 | 반복 10 / 10 | 손실 0.12
| 에폭 273 | 반복 10 / 10 | 손실 0.12
| 에폭 274 | 반복 10 / 10 | 손실 0.12
| 에폭 275 | 반복 10 / 10 | 손실 0.11
| 에폭 276 | 반복 10 / 10 | 손실 0.12
| 에폭 277 | 반복 10 / 10 | 손실 0.12
| 에폭 278 | 반복 10 / 10 | 손실 0.11
| 에폭 279 | 반복 10 / 10 | 손실 0.11
| 에폭 280 | 반복 10 / 10 | 손실 0.11
| 에폭 281 | 반복 10 / 10 | 손실 0.11
| 에폭 282 | 반복 10 / 10 | 손실 0.12
| 에폭 283 | 반복 10 / 10 | 손실 0.11
| 에폭 284 | 반복 10 / 10 | 손실 0.11
| 에폭 285 | 반복 10 / 10 | 손실 0.11
| 에폭 286 | 반복 10 / 10 | 손실 0.11
| 에폭 287 | 반복 10 / 10 | 손실 0.11
| 에폭 288 | 반복 10 / 10 | 손실 0.12
| 에폭 289 | 반복 10 / 10 | 손실 0.11
| 에폭 290 | 반복 10 / 10 | 손실 0.11
| 에폭 291 | 반복 10 / 10 | 손실 0.11
| 에폭 292 | 반복 10 / 10 | 손실 0.11
| 에폭 293 | 반복 10 / 10 | 손실 0.11
| 에폭 294 | 반복 10 / 10 | 손실 0.11
| 에폭 295 | 반복 10 / 10 | 손실 0.12
| 에폭 296 | 반복 10 / 10 | 손실 0.11
| 에폭 297 | 반복 10 / 10 | 손실 0.12
| 에폭 298 | 반복 10 / 10 | 손실 0.11
| 에폭 299 | 반복 10 / 10 | 손실 0.11
| 에폭 300 | 반복 10 / 10 | 손실 0.11
